# fly.toml app configuration file generated for shippify on 2023-10-03T12:23:27+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shippify"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
