// ===========================shipmentDetail======================
const shipmentDetail = {
  _id: "651bf2ae0590ae930a6e8f86",
  user: {
    _id: "650bc6c1da0163755fc319eb",
    name: "user",
    email: "user@user.com",
    password: "$2b$10$PhQW6SLP0ddhd6d7ViPdVO3gxODqs.dPwhYxmSArNUmWkP6xk55My",
    contact: "0123456789",
    selectedCarriers: [],
    shipments: [],
    createdAt: "2023-09-21T04:29:53.022Z",
    updatedAt: "2023-09-21T16:29:27.894Z",
    __v: 0,
    address: {
      address_line1: "4009 Marathon Blvd",
      address_line2: "Suite 300",
      city_locality: "Austin",
      state_province: "TX",
      postal_code: "78756",
      country_code: "US",
      address_residential_indicator: "no",
    },
    companyContact: "string",
    companyEmail: "companyEmail",
    companyLogo: "",
    companyName: "companyName",
    monthlyShipmentValue: "",
    website: "http://what.aht.vom",
  },
  shipment_detail: {
    errors: [],
    address_validation: null,
    shipment_id: "se-804140188",
    carrier_id: null,
    service_code: null,
    external_shipment_id: null,
    shipment_number: null,
    ship_date: "2023-10-03T00:00:00Z",
    created_at: "2023-10-03T10:53:34.3725353Z",
    modified_at: "2023-10-03T10:53:34.3678572Z",
    shipment_status: "pending",
    ship_to: {
      instructions: null,
      name: "Amanda Miller",
      phone: "20 5555 5555",
      email: null,
      company_name: null,
      address_line1: "4412 27 St #203",
      address_line2: null,
      address_line3: null,
      city_locality: "Vernon",
      state_province: "BC",
      postal_code: "V1T 4Y4",
      country_code: "CA",
      address_residential_indicator: "yes",
    },
    ship_from: {
      instructions: null,
      name: "John Doe",
      phone: "512-555-5555",
      email: null,
      company_name: "Example Corp.",
      address_line1: "4009 Marathon Blvd",
      address_line2: null,
      address_line3: null,
      city_locality: "Austin",
      state_province: "TX",
      postal_code: "78756",
      country_code: "US",
      address_residential_indicator: "no",
    },
    warehouse_id: null,
    return_to: {
      instructions: null,
      name: "John Doe",
      phone: "512-555-5555",
      email: null,
      company_name: "Example Corp.",
      address_line1: "4009 Marathon Blvd",
      address_line2: null,
      address_line3: null,
      city_locality: "Austin",
      state_province: "TX",
      postal_code: "78756",
      country_code: "US",
      address_residential_indicator: "no",
    },
    is_return: false,
    confirmation: "none",
    customs: {
      contents: "merchandise",
      contents_explanation: null,
      customs_items: [Array],
      non_delivery: "treat_as_abandoned",
      buyer_shipping_amount_paid: null,
      duties_paid: null,
      terms_of_trade_code: null,
      declaration: null,
      invoice_additional_details: [Object],
      importer_of_record: [Object],
    },
    external_order_id: null,
    order_source_code: null,
    advanced_options: {
      bill_to_account: null,
      bill_to_country_code: null,
      bill_to_party: null,
      bill_to_postal_code: null,
      contains_alcohol: false,
      delivered_duty_paid: false,
      non_machinable: false,
      saturday_delivery: false,
      dry_ice: false,
      dry_ice_weight: null,
      fedex_freight: null,
      third_party_consignee: false,
      ancillary_endorsements_option: null,
      freight_class: null,
      custom_field1: null,
      custom_field2: null,
      custom_field3: null,
      collect_on_delivery: null,
      return_pickup_attempts: null,
      additional_handling: false,
      own_document_upload: false,
    },
    insurance_provider: "none",
    tags: [],
    packages: [[Object]],
    total_weight: { value: 100, unit: "pound" },
    items: [],
  },
  createdAt: "2023-10-03T10:53:34.287Z",
  updatedAt: "2023-10-03T10:55:13.984Z",
  __v: 0,
  rateDetail: {
    rate_id: "se-4218962438",
    rate_type: "shipment",
    carrier_id: "se-5332843",
    shipping_amount: { currency: "usd", amount: 855.93 },
    insurance_amount: { currency: "usd", amount: 0 },
    confirmation_amount: { currency: "usd", amount: 0 },
    other_amount: { currency: "usd", amount: 0 },
    tax_amount: { currency: "usd", amount: 0 },
    rate_details: [],
    zone: null,
    package_type: null,
    delivery_days: 3,
    guaranteed_service: true,
    estimated_delivery_date: "2023-10-06T23:30:00Z",
    carrier_delivery_days: "Friday 10/6 by 11:30 PM",
    ship_date: "2023-10-03T00:00:00Z",
    negotiated_rate: false,
    service_type: "UPS Worldwide Expedited®",
    service_code: "ups_worldwide_expedited",
    trackable: true,
    carrier_code: "ups",
    carrier_nickname: "ShipEngine Test Account - UPS",
    carrier_friendly_name: "UPS",
    validation_status: "valid",
    warning_messages: [],
    error_messages: [],
  },
};
// ===========================payloadForDB======================
const payloadForDB = {
  _id: "651bf2ae0590ae930a6e8f86",
  updateFields: {
    insurance_detail: {
      object: "Insurance",
      mode: "test",
      reference: null,
      status: "pending",
      amount: "30",
      provider: "easypost",
      provider_id: null,
      to_address: [Object],
      from_address: [Object],
      shipment_id: null,
      tracker: null,
      tracking_code: "",
      fee: [Object],
      messages: "",
    },
    labelDetail: {
      label_id: "se-353835281",
      status: "completed",
      shipment_id: "se-804140188",
      ship_date: "2023-10-03T12:53:34.36Z",
      created_at: "2023-10-03T10:55:38.4368418Z",
      shipment_cost: [Object],
      insurance_cost: [Object],
      rate_details: [],
      tracking_number: "1ZXXXXXXXXXXXXXXXX",
      is_return_label: false,
      rma_number: null,
      is_international: true,
      batch_id: "",
      carrier_id: "se-5332843",
      service_code: "ups_worldwide_expedited",
      package_code: "custom_laptop_box",
      voided: false,
      voided_at: null,
      label_format: "pdf",
      display_scheme: "label",
      label_layout: "4x6",
      trackable: true,
      label_image_id: null,
      carrier_code: "ups",
      tracking_status: "in_transit",
      label_download: [Object],
      form_download: [Object],
      qr_code_download: null,
      insurance_claim: null,
      packages: [Array],
      charge_event: "carrier_default",
      alternative_identifiers: [],
    },
    "shipment_detail.shipment_status": "label_purchased",
    payment_detail: { status: "bnpl", net_payable: "400" },
  },
};
